blank_issues_enabled: false
# contact_links:
#   - name: Course Q&A (Piazza / Discussion Forum)
#     url: https://example.com/course-forum
#     about: Use the course forum for general conceptual questions.
#   - name: Emergency Instructor Contact
#     url: https://example.com/contact-instructor
#     about: For critical private matters only. Do NOT post assignment solutions.
